### PR TITLE
Replace the script fs2zef.sh with the Matlab function mri2mesh.fs2zef

### LINKED ISSUE #191: the fs2zef.sh generates colortables, but put them in the wrong direction
### Description
The `fs2zef.sh` generates colortables (color_table_lh_36.mat, color_table_rh_36.mat, color_table_lh_76.mat, color_table_rh_76.mat) but put them in the input directory rather than in output.

### Expectation
`fs2zef.sh` puts files in `$OUT_DIR`

### LINKED ISSUE #192: `fs2zef.sh` improvements
### Suggestions

1. The [`import_segmentation.zef`](https://github.com/sampsapursiainen/zeffiro_interface/blob/master/scripts/scripts_for_importing/mri2mesh/import_segmentation.zef) has a legacy format and I didn’t manage to use it for import. Let’s replace it with a new one - I would suggest to use the [`import_segmentation.zef`](https://github.com/sampsapursiainen/zeffiro_interface/blob/master/scripts/scripts_for_importing/multicompartment_head_project/import_segmentation.zef) but without the first line importing `electrodes.dat` since electrodes are not generated by the script.
2. Also, let’s add the `cp import_segmentation.zef $OUT_DIR/` to the [`fs2zef.sh`](https://github.com/sampsapursiainen/zeffiro_interface/blob/master/scripts/scripts_for_importing/mri2mesh/fs2zef.sh) so it produces a ready-to-import directory.
3. Why the project has 3 different `fs2zef.sh` files? For me it is very confusing even though I spent many hours converting different MRI scans. If we absolutely need to have so many let's at least use different names for them. I would suggest to keep only on and rename it to `freeSurfer2zeffiro.sh`
4. It looks like previously the `fs2zef.sh` was performing the reconstruction with `recon-all` based on this code fragment https://github.com/sampsapursiainen/zeffiro_interface/blob/4b5132d6f9eb5bf46dfff710c6a6558870aa3597/scripts/scripts_for_importing/mri2mesh/fs2zef.sh#L38-L48
Why that code was disabled? Do we want to make the convertation process more difficult and require users to run `recon-all` manually? This may lead to unwanted problems and mistakes.

### PR DESCRIPTION
**Pull request by SeSodesa**
- Add a new function `+mri2mesh/fs2zef.m` that handles the role of the old `fs2zef.sh`.
  Requires at least Matlab R2019a.

- Allow `.dat` files in the subdirectories of this project via `.gitignore`.

- Include updated `import_segmentation.zef` and an example `electrodes.dat` file
  under `+mri2mesh/`.

Closes #191, #192 and #197 . Do not merge until ready.

### CODE REVIEW

File: +mri2mesh/fs2zef.m [hunk 1]
```diff
@@ -0,0 +1,616 @@
...
+
+    if not ( isfolder ( MNI_DIR ) )
+
+        error(fs_dir_not_found_msg("MNI_DIR", "mni"))
+
+    end
+
+    setenv("MNI_DIR", MNI_DIR);
+
+    FSL_DIR = fullfile("/", "usr", "local", "fsl");
```
Comment (mshavliuk) [inline +mri2mesh/fs2zef.m:131]: The `FSL_DIR` path is hardcodded which has caused the error:
```
Checking environment…
Error using mri2mesh.fs2zef (line 135)
The FreeSurfer environment variable FSL_DIR was not set to point to an existing FreeSurfer folder 'fsl'. Set the variable in the shell that started Matlab and try again.
```



Moreover, I didn't manage to find an `fsl` dir on my system by running `find / -type d -name "fsl"`.

File: +mri2mesh/fs2zef.m [hunk 2]
```diff
@@ -0,0 +1,616 @@
...
+
+    end
+
+    if not ( isfolder ( FREESURFER_HOME ) )
+
+        error(fs_dir_not_found_msg("FREESURFER_HOME", "freesurfer (the installation folder)"))
+
+    end
+
+    SUBJECTS_DIR = fullfile(FREESURFER_HOME, "subjects") ;
```
Comment (mshavliuk) [inline +mri2mesh/fs2zef.m:87]: It sets the `SUBJECTS_DIR` variable to `$FREESURFER_HOME/subjects` even though that variable is expected to already exist and have some value, which will be ignored.

Here's the output of `source $FREESURFER_HOME/SetUpFreeSurfer.sh`:
```
-------- freesurfer-darwin-macOS-7.3.2-20220804-6354275 --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /Applications/freesurfer/7.3.2
FSFAST_HOME       /Applications/freesurfer/7.3.2/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /Users/mikhail/freesurfer_subjects
MNI_DIR           /Applications/freesurfer/7.3.2/mni
```

**Review by mshavliuk — CHANGES_REQUESTED** [review]

File: +mri2mesh/fs2zef.m (hunk 1 above)
Comment (SeSodesa) [reply +mri2mesh/fs2zef.m:131]: More thorough checks regarding environment variables should obviously be added, similar to how they are in `$FREESURFER_HOME/FREESURFER_ENV.sh`, which is sourced by `$FREESURFER_HOME/SetUpFreeSurfer.sh`. I'll implement them as soon as possible.

File: +mri2mesh/README.md [hunk 3]
```diff
@@ -0,0 +1,93 @@
+# mri2mesh
```
Comment (mshavliuk) [inline +mri2mesh/README.md:1]: I like how detailed you've described the `fs2zef` function 👍

I wonder, if this readme file is the best place to store the documentation about it or we should better transfer all this content to https://github.com/sampsapursiainen/zeffiro_interface/wiki/Notes:-Importing-Segmentation-from-FreeSurfer wiki page?

I would assume that the user of ZI will rather start from exploring the wiki pages rather than roaming between the source code directories and reading existing files. In case if they don't know if the `mri2mesh` is the tool they need, they will not even open the directory and won't see this documentation. What do you think?

File: scripts/scripts_for_importing/mri2mesh/fs2zef.sh [hunk 4]
```diff
@@ -1,38 +1,65 @@
 #!/bin/bash
```
Comment (mshavliuk) [inline scripts/scripts_for_importing/mri2mesh/fs2zef.sh:1]: What about `scripts/scripts_for_importing/mri2mesh` directory? Do you think it's wise to keep both versions of the script?

I would suggest to stick to a single decision and delete everything that is outdated, so there's no confusion such as "which fs2zef do you mean, .sh or .m" or "which mri2mesh directory, with matlab or with shell"

**Review by mshavliuk — CHANGES_REQUESTED** [review]

File: scripts/scripts_for_importing/mri2mesh/fs2zef.sh (hunk 4 above)
Comment (SeSodesa) [reply scripts/scripts_for_importing/mri2mesh/fs2zef.sh:1]: I absolutely agree that the redundant folders should be done away with. I just want to make sure the Matlab version first works and then do the deletion in one swell commit, dedicated to precisely that and nothing else.

File: +mri2mesh/README.md (hunk 3 above)
Comment (SeSodesa) [reply +mri2mesh/README.md:1]: Yeah, there should be one main source of truth. It makes sense to place the information in the wiki.

File: +mri2mesh/fs2zef.m (hunk 1 above)
Comment (SeSodesa) [reply +mri2mesh/fs2zef.m]: @mshavliuk I changed how the environment variables are loaded, and I'm now crossing my fingers that this bug is done away with. The function should now check for existing variables before setting the values to assumed defaults.

I didn't get much sleep last night and this was done while being completely cross-eyed, so please tell me if something is still amiss on your end.

Comment (mshavliuk) [reply +mri2mesh/fs2zef.m]: Now this seems to work properly! I didn't face any issues with FSL even though it's not installed on my system

**Review by mshavliuk — APPROVED** [review]
Awesome job, everything seems to work smoothly ✨

Let's also not forget to (in another PR?):
- [ ] Remove an outdated fs2zef.sh script
- [ ] Move the documentation to the wiki page and refer to it from the readme.md or from the script file itself

**Comment by SeSodesa** [comment]
> Awesome job, everything seems to work smoothly ✨
> 
> Let's also not forget to (in another PR?):
> 
>     * [ ]  Remove an outdated fs2zef.sh script
> 
>     * [ ]  Move the documentation to the wiki page and refer to it from the readme.md or from the script file itself

The `README` from `+mri2mesh` should already be on the Wiki pages ([link]). We might consider that item resolved already, unless there is still something that could be improved on the page.

[link]: https://github.com/sampsapursiainen/zeffiro_interface/wiki/Importing-a-Segmentation-from-FreeSurfer

**Comment by SeSodesa** [comment]
I think I will squash the commits and merge this, then, since the `README` has already been copied over to the wiki pages. We can do the removal of the old redundant files in a separate context, dedicated to it and only it. This will make it easier to find a point in the project history where the removal was done, in case something will be missed.
